<?xml version="1.0"?>
<package format="3">
  <name>rosie_grasp</name>
  <version>0.1.0</version>
  <description>Contact-GraspNet adapter for Rosie manipulation.</description>
  <maintainer email="samson@samsonajadalu.com">Samson Ajadalu</maintainer>
  <license>BSD-3-Clause</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>tf2_geometry_msgs</exec_depend>
  <exec_depend>message_filters</exec_depend>
  <exec_depend>cv_bridge</exec_depend>
  <exec_depend>yolov8_msgs</exec_depend>
  <exec_depend>python3-numpy</exec_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
